import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import RegisterSW from "./RegisterSW";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  minimumScale: 1,
  width: "device-width",
  interactiveWidget: "resizes-content",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RegisterSW />
        <div className="">
          <div className="flex gap-3 p-2">
            <Link href={"/ai-chat"}>Ai Chat</Link>
            <Link href={"/chats"}>Chats Render</Link>
            <Link href={"/effect"}>Effect</Link>
            <Link href={"/layout-test"}>Layout test</Link>
            <Link href={"/otp"}>OTP</Link>
            <Link href={"/api-sample"}>API Sample</Link>
            <Link href={"/checkbox"}>Checkboxes</Link>
            <Link href={"/sliders"}>Slider</Link>
            <Link href={"/use-transition"}>useTransition</Link>
            <Link href={"/virtualize"}>Virtualized</Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
